# Generated by Django 4.2.6 on 2023-11-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0003_rename_pos_index_article_z_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composingtemplate',
            name='file_type',
            field=models.CharField(default='JPEG', max_length=10),
        ),
    ]
