# Generated by Django 4.2.6 on 2023-11-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0008_article_pos_index_composingarticletemplate_pos_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_transparent',
            field=models.BooleanField(default=False),
        ),
    ]
