# Generated by Django 4.2.6 on 2023-11-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0011_alter_composing_png_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composingtemplate',
            name='resolution_dpi',
            field=models.IntegerField(default=144),
        ),
    ]
