# Generated by Django 4.2.6 on 2023-11-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0002_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pos_index',
            new_name='z_index',
        ),
        migrations.RemoveField(
            model_name='composingarticletemplate',
            name='pos_index',
        ),
    ]
