# Generated by Django 4.2.6 on 2023-11-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0005_article_prod_left_article_prod_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='composing',
            name='cdn_url',
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
