# Generated by Django 4.2.6 on 2023-11-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0006_composing_cdn_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prod_left',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prod_top',
        ),
        migrations.RemoveField(
            model_name='article',
            name='transparent_cdn_url',
        ),
    ]
