# Generated by Django 4.2.6 on 2023-11-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0007_remove_article_prod_left_remove_article_prod_top_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pos_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='composingarticletemplate',
            name='pos_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
