# Generated by Django 4.2.6 on 2023-11-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0013_remove_article_render_url_remove_article_tiff_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composingtemplate',
            name='bg_image_tiff_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composingtemplate',
            name='resolution_dpi',
            field=models.IntegerField(default=144),
        ),
    ]
