# Generated by Django 4.2.6 on 2024-01-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0014_composingtemplate_bg_image_tiff_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scaling',
            field=models.FloatField(),
        ),
    ]
